---
deployment:
  tasks:
    - export DEPLOYPATH=/home/discomau/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp resume.html $DEPLOYPATH
    - /bin/cp 404.html $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp enquire.php $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp favicon-192.png $DEPLOYPATH
    - /bin/cp favicon-512.png $DEPLOYPATH
    - /bin/cp apple-touch-icon.png $DEPLOYPATH
    - /bin/cp 417dc36f9b138ad76d99724e9e558919.txt $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R google-ads-management $DEPLOYPATH
    - /bin/cp -R seo-and-content $DEPLOYPATH
    - /bin/cp -R graphic-design $DEPLOYPATH
    - /bin/cp -R web-and-digital $DEPLOYPATH
    - /bin/cp -R portfolio $DEPLOYPATH
